/**
 * Seeding script: generates golden dataset JSON fixtures by calling the
 * TypeScript limit functions directly.
 *
 * Usage: npx ts-node -P tsconfig.seed.json test/fixtures/golden/generators/seed.ts
 *
 */
import * as fs from "fs";
import * as path from "path";
import * as limitFunctions from "../../../../src/Limit Calculations";

// ---------- Types ----------

type GoldenDataset = {
  metadata: {
    chart_type: string;
    scenario: string;
    source: string;
    reference: string;
    generated_date: string;
    precision: number;
  };
  inputs: {
    keys: string[];
    numerators: number[];
    denominators?: number[] | null;
    xbar_sds?: number[] | null;
    outliers_in_limits?: boolean;
  };
  expected: Record<string, number[]>;
};

// ---------- Helpers ----------

function buildArgs(opts: {
  keys: string[];
  numerators: number[];
  denominators?: number[];
  xbar_sds?: number[];
  outliers_in_limits?: boolean;
}) {
  const n = opts.keys.length;
  return {
    keys: opts.keys.map((label, i) => ({ x: i, id: i, label })),
    numerators: opts.numerators,
    denominators: opts.denominators ?? [],
    xbar_sds: opts.xbar_sds,
    subset_points: Array.from({ length: n }, (_, i) => i),
    outliers_in_limits: opts.outliers_in_limits ?? true,
  };
}

function round(arr: number[], digits: number): number[] {
  const factor = Math.pow(10, digits);
  return arr.map((v) => Math.round(v * factor) / factor);
}

function extractExpected(
  result: any,
  precision: number,
  includeValues: boolean = true
): Record<string, number[]> {
  const expected: Record<string, number[]> = {};
  expected.targets = round(result.targets, precision + 2);
  if (includeValues) {
    expected.values = round(result.values, precision + 2);
  }
  if (result.ul99) expected.ul99 = round(result.ul99, precision + 2);
  if (result.ul95) expected.ul95 = round(result.ul95, precision + 2);
  if (result.ul68) expected.ul68 = round(result.ul68, precision + 2);
  if (result.ll68) expected.ll68 = round(result.ll68, precision + 2);
  if (result.ll95) expected.ll95 = round(result.ll95, precision + 2);
  if (result.ll99) expected.ll99 = round(result.ll99, precision + 2);
  return expected;
}

function writeGolden(golden: GoldenDataset): void {
  const dir = path.resolve(
    __dirname,
    "..",
    golden.metadata.chart_type
  );
  fs.mkdirSync(dir, { recursive: true });
  const filePath = path.join(dir, `${golden.metadata.scenario}.json`);
  fs.writeFileSync(filePath, JSON.stringify(golden, null, 2) + "\n");
  console.log(`  Written: ${filePath}`);
}

const TODAY = new Date().toISOString().slice(0, 10);
const SOURCE = "TYPESCRIPT-SEEDED: Generated by running PowerBI-SPC limit functions directly. " +
  "These are NOT independently validated. Run generate_golden.R to produce " +
  "qicharts2-validated reference files (.qicharts2.json) for cross-validation.";

// ===================== DATASETS =====================

// --- I-chart (ratio) ---
const iKeys = ["2010-01-01","2010-02-01","2010-03-01","2010-04-01","2010-05-01","2010-06-01","2010-07-01","2010-08-01","2010-09-01","2010-10-01","2010-11-01","2010-12-01","2011-01-01","2011-02-01","2011-03-01","2011-04-01","2011-05-01"];
const iNum = [5,7,5,7,7,5,4,9,8,13,8,7,8,7,12,11,8];
const iDen = [113,132,121,134,116,131,93,138,182,157,100,103,146,108,153,141,134];

{
  const args = buildArgs({ keys: iKeys, numerators: iNum, denominators: iDen });
  const result = limitFunctions.i(args);
  writeGolden({
    metadata: { chart_type: "i", scenario: "basic-ratio", source: SOURCE, reference: "Montgomery 2009, Chapter 6", generated_date: TODAY, precision: 4 },
    inputs: { keys: iKeys, numerators: iNum, denominators: iDen },
    expected: extractExpected(result, 4),
  });
}

// --- MR-chart (ratio) ---
{
  const args = buildArgs({ keys: iKeys, numerators: iNum, denominators: iDen });
  const result = limitFunctions.mr(args);
  writeGolden({
    metadata: { chart_type: "mr", scenario: "basic-ratio", source: SOURCE, reference: "Montgomery 2009, Chapter 6", generated_date: TODAY, precision: 4 },
    inputs: { keys: iKeys, numerators: iNum, denominators: iDen },
    expected: extractExpected(result, 4),
  });
}

// --- C-chart (group 1 only: first 24 points) ---
const cKeysAll = ["2012-11-01","2012-12-01","2013-01-01","2013-02-01","2013-03-01","2013-04-01","2013-05-01","2013-06-01","2013-07-01","2013-08-01","2013-09-01","2013-10-01","2013-11-01","2013-12-01","2014-01-01","2014-02-01","2014-03-01","2014-04-01","2014-05-01","2014-06-01","2014-07-01","2014-08-01","2014-09-01","2014-10-01","2014-11-01","2014-12-01","2015-01-01","2015-02-01","2015-03-01","2015-04-01","2015-05-01","2015-06-01","2015-07-01","2015-08-01","2015-09-01","2015-10-01"];
const cNumAll = [17,12,27,20,20,18,22,19,19,24,17,16,24,19,19,22,25,19,17,6,25,17,11,14,9,11,7,13,5,5,3,5,9,4,5,9];
const cKeysG1 = cKeysAll.slice(0, 24);
const cNumG1 = cNumAll.slice(0, 24);

{
  const args = buildArgs({ keys: cKeysG1, numerators: cNumG1 });
  const result = limitFunctions.c(args);
  writeGolden({
    metadata: { chart_type: "c", scenario: "basic-group1", source: SOURCE, reference: "Montgomery 2009, Chapter 7 (Poisson counts)", generated_date: TODAY, precision: 2 },
    inputs: { keys: cKeysG1, numerators: cNumG1 },
    expected: extractExpected(result, 2),
  });
}

// --- P-chart ---
const pKeys = ["2011-07-01","2011-08-01","2011-09-01","2011-10-01","2011-11-01","2011-12-01","2012-01-01","2012-02-01","2012-03-01","2012-04-01","2012-05-01","2012-06-01","2012-07-01","2012-08-01","2012-09-01","2012-10-01","2012-11-01","2012-12-01","2013-01-01","2013-02-01","2013-03-01","2013-04-01","2013-05-01","2013-06-01","2013-07-01","2013-08-01","2013-09-01","2013-10-01","2013-11-01","2013-12-01","2014-01-01","2014-02-01","2014-03-01","2014-04-01","2014-05-01","2014-06-01"];
const pNum = [14,12,15,8,16,11,12,14,16,17,5,11,13,10,14,5,12,10,11,5,10,8,11,12,11,18,18,21,14,15,18,22,17,16,20,15];
const pDen = [52,64,70,60,67,69,67,54,79,59,49,61,41,51,56,43,57,48,69,41,40,46,59,62,57,65,75,70,76,69,64,67,84,67,69,78];

{
  const args = buildArgs({ keys: pKeys, numerators: pNum, denominators: pDen });
  const result = limitFunctions.p(args);
  writeGolden({
    metadata: { chart_type: "p", scenario: "basic", source: SOURCE, reference: "Montgomery 2009, Chapter 7 (Binomial proportions)", generated_date: TODAY, precision: 2 },
    inputs: { keys: pKeys, numerators: pNum, denominators: pDen },
    expected: extractExpected(result, 2),
  });
}

// --- G-chart ---
const gKeys = Array.from({ length: 67 }, (_, i) => String(i + 1));
const gNum = [23,39,15,34,1,49,98,29,27,13,45,7,10,27,24,14,20,38,44,11,10,3,113,183,3,47,18,18,33,15,2,38,27,27,1,52,23,7,26,82,5,49,5,17,24,44,26,2,27,46,55,97,22,22,20,4,60,51,7,21,66,36,25,72,15,5,3];

{
  const args = buildArgs({ keys: gKeys, numerators: gNum });
  const result = limitFunctions.g(args);
  writeGolden({
    metadata: { chart_type: "g", scenario: "basic", source: SOURCE, reference: "Benneyan 1998, Geometric distribution SPC", generated_date: TODAY, precision: 2 },
    inputs: { keys: gKeys, numerators: gNum },
    expected: extractExpected(result, 2),
  });
}

// --- T-chart ---
const tKeys = Array.from({ length: 67 }, (_, i) => String(i + 1));
const tNum = [16,20,5,13,1,26,46,12,12,5,19,4,3,15,14,9,8,15,21,6,3,1,56,117,1,33,9,9,19,12,1,16,13,18,1,35,16,5,21,38,3,25,3,11,13,20,9,3,8,21,24,38,8,13,9,1,30,23,3,7,22,19,11,31,6,1,1];

{
  const args = buildArgs({ keys: tKeys, numerators: tNum });
  const result = limitFunctions.t(args);
  writeGolden({
    metadata: { chart_type: "t", scenario: "basic", source: SOURCE, reference: "Nelson 1994, T-chart for time between events", generated_date: TODAY, precision: 2 },
    inputs: { keys: tKeys, numerators: tNum },
    expected: extractExpected(result, 2),
  });
}

// --- S-chart ---
const sSds = [8.69,8.86,10.16,10.45,10.12,8.94,9.51,9.53,11.22,8.5,9.04,10.82,8.8,9.65,10.41,10.08,9.7,9.35,8.5,9.59,9.72,8.89,9.99,10.74,9.68,9.63,9.74,10.35,8.65,9.88,7.9,8.95,9.45,9.81,8.58,11.19];
const sDen = [52,64,70,60,67,69,67,54,79,59,49,61,41,51,56,43,57,48,69,41,40,46,59,62,57,65,75,70,76,69,64,67,84,67,69,78];

{
  const args = buildArgs({ keys: pKeys, numerators: sSds, denominators: sDen });
  const result = limitFunctions.s(args);
  writeGolden({
    metadata: { chart_type: "s", scenario: "basic", source: SOURCE, reference: "Montgomery 2009, Chapter 6 (S-chart)", generated_date: TODAY, precision: 2 },
    inputs: { keys: pKeys, numerators: sSds, denominators: sDen },
    expected: extractExpected(result, 2),
  });
}

// --- XBar-chart ---
const xbarNum = [66.88,68.76,67.75,67.05,67.2,67.43,69.23,71.12,67.63,69.97,66.67,67.76,69.32,66.04,67.61,69.69,67.62,67.31,68.41,64.73,68.28,69.34,66.53,66.67,67.27,67.69,67.6,67.29,68.47,66.82,68.87,66.75,67.41,69.87,68.19,66.04];
const xbarSds = [8.69,8.86,10.16,10.45,10.12,8.94,9.51,9.53,11.22,8.5,9.04,10.82,8.8,9.65,10.41,10.08,9.7,9.35,8.5,9.59,9.72,8.89,9.99,10.74,9.68,9.63,9.74,10.35,8.65,9.88,7.9,8.95,9.45,9.81,8.58,11.19];

{
  const args = buildArgs({ keys: pKeys, numerators: xbarNum, denominators: sDen, xbar_sds: xbarSds });
  const result = limitFunctions.xbar(args);
  writeGolden({
    metadata: { chart_type: "xbar", scenario: "basic", source: SOURCE, reference: "Montgomery 2009, Chapter 6 (X-bar chart)", generated_date: TODAY, precision: 2 },
    inputs: { keys: pKeys, numerators: xbarNum, denominators: sDen, xbar_sds: xbarSds },
    expected: extractExpected(result, 2),
  });
}

// --- U-chart (raw, no multiplier) ---
const uKeys = ["2015-01-01","2015-02-01","2015-03-01","2015-04-01","2015-05-01","2015-06-01","2015-07-01","2015-08-01","2015-09-01","2015-10-01","2015-11-01","2015-12-01","2016-01-01","2016-02-01","2016-03-01","2016-04-01","2016-05-01","2016-06-01","2016-07-01","2016-08-01","2016-09-01","2016-10-01","2016-11-01","2016-12-01"];
const uNum = [575,521,585,528,507,519,457,505,494,512,543,506,509,521,549,531,509,528,419,512,495,513,454,490];
const uDen = [310466.8333,282346.7917,309089.7083,287977.3333,297743.375,286988.25,261120.3333,268720.75,284437.875,290449.5,288104.4583,279961.375,289803.9583,275950.5833,290824.4583,285495.75,282515.2083,273927.875,253085.625,262410.7083,275529.25,282405.0833,259530.7917,256235.4583];

{
  const args = buildArgs({ keys: uKeys, numerators: uNum, denominators: uDen });
  const result = limitFunctions.u(args);
  writeGolden({
    metadata: { chart_type: "u", scenario: "basic", source: SOURCE, reference: "Montgomery 2009, Chapter 7 (Rate per unit)", generated_date: TODAY, precision: 6 },
    inputs: { keys: uKeys, numerators: uNum, denominators: uDen },
    expected: extractExpected(result, 6),
  });
}

// --- P'-chart ---
const ppKeys = Array.from({ length: 20 }, (_, i) => String(i + 1));
const ppNum = [266501,264225,276532,281461,269071,261215,270409,279778,270483,270320,267923,271478,255353,256820,261835,259144,255910,260863,264465,260989];
const ppDen = [280443,276823,291681,296155,282343,275888,283867,295251,284468,282529,279618,283932,266629,268091,276803,271578,266005,273520,278574,273772];

{
  const args = buildArgs({ keys: ppKeys, numerators: ppNum, denominators: ppDen });
  const result = limitFunctions.pp(args);
  writeGolden({
    metadata: { chart_type: "pp", scenario: "basic", source: SOURCE, reference: "Laney 2002, P-prime chart with MR-based sigma", generated_date: TODAY, precision: 4 },
    inputs: { keys: ppKeys, numerators: ppNum, denominators: ppDen },
    expected: extractExpected(result, 4),
  });
}

// --- U'-chart ---
{
  const args = buildArgs({ keys: ppKeys, numerators: ppNum, denominators: ppDen });
  const result = limitFunctions.up(args);
  writeGolden({
    metadata: { chart_type: "up", scenario: "basic", source: SOURCE, reference: "Laney 2002, U-prime chart with MR-based sigma", generated_date: TODAY, precision: 4 },
    inputs: { keys: ppKeys, numerators: ppNum, denominators: ppDen },
    expected: extractExpected(result, 4),
  });
}

// --- I-median chart ---
const imKeys = ["2020-01-01","2020-02-01","2020-03-01","2020-04-01","2020-05-01","2020-06-01","2020-07-01","2020-08-01","2020-09-01","2020-10-01","2020-11-01","2020-12-01","2021-01-01","2021-02-01","2021-03-01","2021-04-01","2021-05-01","2021-06-01"];
const imNum = [12,15,11,18,14,13,16,19,12,14,17,11,15,13,16,18,12,14];

{
  const args = buildArgs({ keys: imKeys, numerators: imNum });
  const result = limitFunctions.i_m(args);
  writeGolden({
    metadata: { chart_type: "i_m", scenario: "basic", source: SOURCE, reference: "I-chart with median centreline", generated_date: TODAY, precision: 4 },
    inputs: { keys: imKeys, numerators: imNum },
    expected: extractExpected(result, 4),
  });
}

// --- I-median-MR chart ---
{
  const args = buildArgs({ keys: imKeys, numerators: imNum });
  const result = limitFunctions.i_mm(args);
  writeGolden({
    metadata: { chart_type: "i_mm", scenario: "basic", source: SOURCE, reference: "I-chart with median centreline and median MR", generated_date: TODAY, precision: 4 },
    inputs: { keys: imKeys, numerators: imNum },
    expected: extractExpected(result, 4),
  });
}

// --- Run chart ---
{
  const args = buildArgs({ keys: imKeys, numerators: imNum });
  const result = limitFunctions.run(args);
  writeGolden({
    metadata: { chart_type: "run", scenario: "basic", source: SOURCE, reference: "Carey 2003, Run chart (median only)", generated_date: TODAY, precision: 5 },
    inputs: { keys: imKeys, numerators: imNum },
    expected: extractExpected(result, 5),
  });
}

console.log("\nAll golden datasets seeded successfully.");
