name: Test Build PowerBI visual

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    paths-ignore:
      - PowerBI-SPC-Docs/** # Don't run on docs folder

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6

    - name: Setup Node 24
      uses: actions/setup-node@v6
      with:
        node-version: 24
        cache: 'npm'

    - name: Install PBI visual Tools
      run: |
        npm install -g powerbi-visuals-tools@6.2.0

    - name: Install Package Dependencies
      run: |
        npm ci

    - name: Run linter
      run: |
        pbiviz lint

    - name: Test if package can be built
      run: |
        pbiviz package

    - name: Run unit tests
      run: |
        npm run test

    - name: Attach built visual
      if: success()
      uses: actions/upload-artifact@v7
      with:
        name: powerbi-visual-${{ github.sha }}
        path: dist/*.pbiviz
